/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as NecesitoComidaRouteImport } from './routes/necesito-comida'
import { Route as PreguntasRouteImport } from './routes/preguntas'
import { Route as PuntosDeRepartoRouteImport } from './routes/puntos-de-reparto'
import { Route as QueEsCadaPerlaRouteImport } from './routes/que-es-cada-perla'
import { Route as QuieroAyudarRouteImport } from './routes/quiero-ayudar'
import { Route as AyudaCategoriaRouteImport } from './routes/ayuda/$categoria'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const NecesitoComidaRoute = NecesitoComidaRouteImport.update({
  id: '/necesito-comida',
  path: '/necesito-comida',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasRoute = PreguntasRouteImport.update({
  id: '/preguntas',
  path: '/preguntas',
  getParentRoute: () => rootRouteImport,
} as any)
const PuntosDeRepartoRoute = PuntosDeRepartoRouteImport.update({
  id: '/puntos-de-reparto',
  path: '/puntos-de-reparto',
  getParentRoute: () => rootRouteImport,
} as any)
const QueEsCadaPerlaRoute = QueEsCadaPerlaRouteImport.update({
  id: '/que-es-cada-perla',
  path: '/que-es-cada-perla',
  getParentRoute: () => rootRouteImport,
} as any)
const QuieroAyudarRoute = QuieroAyudarRouteImport.update({
  id: '/quiero-ayudar',
  path: '/quiero-ayudar',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaCategoriaRoute = AyudaCategoriaRouteImport.update({
  id: '/ayuda/$categoria',
  path: '/ayuda/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/mapa': typeof MapaRoute
  '/necesito-comida': typeof NecesitoComidaRoute
  '/preguntas': typeof PreguntasRoute
  '/puntos-de-reparto': typeof PuntosDeRepartoRoute
  '/que-es-cada-perla': typeof QueEsCadaPerlaRoute
  '/quiero-ayudar': typeof QuieroAyudarRoute
  '/ayuda/$categoria': typeof AyudaCategoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/mapa': typeof MapaRoute
  '/necesito-comida': typeof NecesitoComidaRoute
  '/preguntas': typeof PreguntasRoute
  '/puntos-de-reparto': typeof PuntosDeRepartoRoute
  '/que-es-cada-perla': typeof QueEsCadaPerlaRoute
  '/quiero-ayudar': typeof QuieroAyudarRoute
  '/ayuda/$categoria': typeof AyudaCategoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/mapa': typeof MapaRoute
  '/necesito-comida': typeof NecesitoComidaRoute
  '/preguntas': typeof PreguntasRoute
  '/puntos-de-reparto': typeof PuntosDeRepartoRoute
  '/que-es-cada-perla': typeof QueEsCadaPerlaRoute
  '/quiero-ayudar': typeof QuieroAyudarRoute
  '/ayuda/$categoria': typeof AyudaCategoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/mapa'
    | '/necesito-comida'
    | '/preguntas'
    | '/puntos-de-reparto'
    | '/que-es-cada-perla'
    | '/quiero-ayudar'
    | '/ayuda/$categoria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/mapa'
    | '/necesito-comida'
    | '/preguntas'
    | '/puntos-de-reparto'
    | '/que-es-cada-perla'
    | '/quiero-ayudar'
    | '/ayuda/$categoria'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/mapa'
    | '/necesito-comida'
    | '/preguntas'
    | '/puntos-de-reparto'
    | '/que-es-cada-perla'
    | '/quiero-ayudar'
    | '/ayuda/$categoria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  MapaRoute: typeof MapaRoute
  NecesitoComidaRoute: typeof NecesitoComidaRoute
  PreguntasRoute: typeof PreguntasRoute
  PuntosDeRepartoRoute: typeof PuntosDeRepartoRoute
  QueEsCadaPerlaRoute: typeof QueEsCadaPerlaRoute
  QuieroAyudarRoute: typeof QuieroAyudarRoute
  AyudaCategoriaRoute: typeof AyudaCategoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/necesito-comida': {
      id: '/necesito-comida'
      path: '/necesito-comida'
      fullPath: '/necesito-comida'
      preLoaderRoute: typeof NecesitoComidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas': {
      id: '/preguntas'
      path: '/preguntas'
      fullPath: '/preguntas'
      preLoaderRoute: typeof PreguntasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puntos-de-reparto': {
      id: '/puntos-de-reparto'
      path: '/puntos-de-reparto'
      fullPath: '/puntos-de-reparto'
      preLoaderRoute: typeof PuntosDeRepartoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/que-es-cada-perla': {
      id: '/que-es-cada-perla'
      path: '/que-es-cada-perla'
      fullPath: '/que-es-cada-perla'
      preLoaderRoute: typeof QueEsCadaPerlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiero-ayudar': {
      id: '/quiero-ayudar'
      path: '/quiero-ayudar'
      fullPath: '/quiero-ayudar'
      preLoaderRoute: typeof QuieroAyudarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda/$categoria': {
      id: '/ayuda/$categoria'
      path: '/ayuda/$categoria'
      fullPath: '/ayuda/$categoria'
      preLoaderRoute: typeof AyudaCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  MapaRoute: MapaRoute,
  NecesitoComidaRoute: NecesitoComidaRoute,
  PreguntasRoute: PreguntasRoute,
  PuntosDeRepartoRoute: PuntosDeRepartoRoute,
  QueEsCadaPerlaRoute: QueEsCadaPerlaRoute,
  QuieroAyudarRoute: QuieroAyudarRoute,
  AyudaCategoriaRoute: AyudaCategoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
